### PR TITLE
Fix paring error of annotations on constructor parameters - 2

### LINKED ISSUE #173: Parsing error of constructor parameters with annotation
Parsing of constructor parameters with annotation is not supported.

Example:

```kotlin
annotation class Ann
class Example(
    @field : Ann
    val foo : String,
    @get : Ann
    val bar : String
) {
}
```

### PR DESCRIPTION
**Pull request by kunli2**
Fixes #173 .

https://github.com/openrewrite/rewrite-kotlin/pull/175 is the 1st approach to fix this problem. 
Discussed with @traceyyoshima that one might break something since we should not parse `fake` kind FIR element (generated by the compiler but not in the source code).
This is a 2nd approach to fix #173

### CODE REVIEW

File: src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java [hunk 1]
```diff
@@ -3451,6 +3467,9 @@ public J visitRegularClass(FirRegularClass regularClass, ExecutionContext ctx) {
                 jcEnums.add(declaration);
             } else if (declaration instanceof FirPrimaryConstructor) {
                 firPrimaryConstructor = (FirPrimaryConstructor) declaration;
+            } else if (declaration instanceof FirProperty && declaration.getSource().getKind() instanceof KtFakeSourceElementKind.PropertyFromParameter) {
```
Comment (traceyyoshima) [inline src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java:3470]: getSource on FirElements is nullable, so we need to check `declaration.getSource() != null`

**Review by traceyyoshima — APPROVED** [review]
Interesting solution, nice job.
Minor comment to prevent NPE.

File: src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java (hunk 1 above)
Comment (kunli2) [reply src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java]: revised.
