### PR TITLE
Fixed import type resolution and super type references.

### LINKED ISSUE #344: Constructor type of anonymous objects is null
The Java symbols include a unique name for anonymous classes, so each constructor is unique like `Test$1`, `Test$2`.

We can derive the constructor type from the anonymous object symbol, but the type is based on the original declaration `Test`.

TBD:
The Kotlin compiler creates signatures and maps types through the IR during the backend phase of compilation, which happens after the transformation from the PSI to the FIR.

This type of issue might be resolved by converting the FIR to the IR and using the mapped types.

```
open class Test
val o1  : Test   =  object   :     Test  (   )     {    }
val o2  : Test   =  object   :     Test  (   )     {
    val     s      :       String        =  ""
}
```

### LINKED ISSUE #376: `J$ParameterizedType` cannot be cast to class `MethodCall`
The following test
```java
    @Test
    void error() {
        rewriteRun(
          kotlin(
            """
              val x: MutableMap<String, String> = hashMapOf()
              val keys = x.entries.map(MutableMap.MutableEntry<String, String>::key)
              """
          )
        );
    }
```
results in the following error:
```
Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.J$ParameterizedType cannot be cast to class org.openrewrite.java.tree.MethodCall (org.openrewrite.java.tree.J$ParameterizedType and org.openrewrite.java.tree.MethodCall are in unnamed module of loader 'app')
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:2283)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallableReferenceExpression(KotlinTreeParserVisitor.java:284)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallableReferenceExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtCallableReferenceExpression.accept(KtCallableReferenceExpression.java:51)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitArgument(KotlinTreeParserVisitor.java:1726)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitArgument(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtValueArgument.accept(KtValueArgument.java:46)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.mapFunctionCallArguments(KotlinTreeParserVisitor.java:3766)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallExpression(KotlinTreeParserVisitor.java:1890)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:2283)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitProperty(KotlinTreeParserVisitor.java:2749)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitProperty(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:58)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitKtFile(KotlinTreeParserVisitor.java:1649)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.parse(KotlinTreeParserVisitor.java:104)
	at org.openrewrite.kotlin.KotlinParser.lambda$parseInputs$4(KotlinParser.java:185)
	... 18 more
```

### PR DESCRIPTION
**Pull request by traceyyoshima**
Changes:

- Added type mapping and signature support for `FirAnonymousObject`, `FirImport` and `FirSuperReference`.
- `KotlinTypeMapping#classType()` will attempt to resolve the `FirClassLikeSymbol` if a `FirRegularClassSymbol` is not available to generate types for anonymous objects.
- An UnsupportedOperationException will be thrown if an FIR tree is not supported instead of returning an empty string.

fixes #344
fixes #376

### CODE REVIEW

File: src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt [hunk 1]
```diff
@@ -957,8 +982,7 @@ class KotlinTypeMapping(
         clazz = if (type.classifier != null) {
             TypeUtils.asFullyQualified(type(type.classifier!!))
         } else {
-            val fq : JavaType = buildType(type.classifierQualifiedName)
-            fq as FullyQualified
+            createShallowClass(type.classifierQualifiedName)
```
Comment (traceyyoshima) [inline src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt:985]: Info:
`buildType(type.classifierQualifiedName)` either creates a `JavaType.Primitive` or a `ShallowClass`, and a primitive is never valid. So, we use `createShallowClass` to create a `ShallowClass`, which also caches the signature for the type.

File: src/main/kotlin/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.kt [hunk 2]
```diff
@@ -180,6 +189,23 @@ class KotlinTypeSignatureBuilder(private val firSession: FirSession, private val
         }
     }
 
+    private fun anonymousClassSignature(type: FirAnonymousObject): String {
+        val sig = StringBuilder(type.symbol.classId.asFqNameString())
+        for (supertype in type.superTypeRefs) {
```
Comment (traceyyoshima) [inline src/main/kotlin/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.kt:194]: Note:
AnonymousObjects in Java include a unique ID like $1, $2, etc.

In Kotlin, each anonymous object is named `<anonymous>` in the FIR. So, we append the super-types to the name to distinguish the signature.

File: src/main/kotlin/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.kt [hunk 3]
```diff
@@ -194,7 +220,7 @@ class KotlinTypeSignatureBuilder(private val firSession: FirSession, private val
             is FirResolvedTypeRef -> classSignature(type.type)
             is FirResolvedQualifier -> convertClassIdToFqn(type.classId)
             else -> {
-                ""
+                throw UnsupportedOperationException("Unsupported class type: ${type.javaClass.name}")
```
Comment (traceyyoshima) [inline src/main/kotlin/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.kt:223]: Each of these blank signatures is a mistake and can cause type issues since the first cached type will be returned for each type that returns a blank signature.
