### PR TITLE
Associate the inner classes to the PSI.

### LINKED ISSUE #517: PSI to FIR association issue: Incorrect on parent classes.
```kotlin
                  class A {
                      class B {
                          class C
                      }
                  }
                  val c = A.B.C()
```

Both A and B will have the same type, `A$B`.

### PR DESCRIPTION
**Pull request by traceyyoshima**
Changes:

- Nested classes will have the correct type attribution.

fixes #517

### CODE REVIEW

File: src/main/kotlin/org/openrewrite/kotlin/internal/PsiElementAssociations.kt [hunk 1]
```diff
@@ -152,9 +149,41 @@ class PsiElementAssociations(val typeMapping: KotlinTypeMapping, val file: FirFi
...
         return if (fir != null) typeMapping.type(fir, owner) else null
     }
 
+    private fun isPackage(psi: PsiElement, classId: ClassId): Boolean {
+        return !classId.packageFqName.isRoot && psi.parent.text == classId.packageFqName.asString()
+    }
+
+    private fun isOuterMostPsi(psi: PsiElement, classId: ClassId): Boolean {
+        val parts = psi.parent.text.split(".")
+        return classId.packageFqName.isRoot && parts.size == 2 && psi.text == parts[0]
```
Comment (kunli2) [inline src/main/kotlin/org/openrewrite/kotlin/internal/PsiElementAssociations.kt:172]: Why it's 2?

Comment (traceyyoshima) [reply src/main/kotlin/org/openrewrite/kotlin/internal/PsiElementAssociations.kt:172]: I'll rename the method and add comments :)
