### PR TITLE
Set constructor type on enum values.

### LINKED ISSUE #533: PSI association issue: parser visitor sets enum constructors to null
```kotlin
              enum class Code {
                  YES ,
              }
              enum class Test ( val arg: Code , ) {
                  FOO ( Code.YES , ) {
                      // Body is required to reproduce issue
                  }
              }
```

### PR DESCRIPTION
**Pull request by traceyyoshima**
EnumValues will contain the constructor type instead of null.
fixes #533

### CODE REVIEW

File: src/main/java/org/openrewrite/kotlin/internal/KotlinTreeParserVisitor.java [hunk 1]
```diff
@@ -494,14 +494,12 @@ public J visitEnumEntry(KtEnumEntry enumEntry, ExecutionContext data) {
...
 
-        // TODO: in java the EnumValue has a type of JavaType.Variable with a null fieldType.
         J.Identifier name = createIdentifier(requireNonNull(enumEntry.getNameIdentifier()), type(enumEntry), consumedSpaces);
         J.NewClass initializer = null;
 
         if (enumEntry.getInitializerList() != null) {
-            // TODO: this creates an empty init with no type attribution: enum class Foo { BAR() }
-            //   Add constructor method type.
             initializer = (J.NewClass) enumEntry.getInitializerList().accept(this, data);
+            initializer = initializer.withMethodType(methodDeclarationType(enumEntry));
```
Comment (kunli2) [inline src/main/java/org/openrewrite/kotlin/internal/KotlinTreeParserVisitor.java:502]: nit: we can have a variable here for `methodDeclarationType(enumEntry)` to save a method invocation.

**Review by kunli2 — APPROVED** [review]

File: src/main/java/org/openrewrite/kotlin/internal/KotlinTreeParserVisitor.java (hunk 1 above)
Comment (traceyyoshima) [reply src/main/java/org/openrewrite/kotlin/internal/KotlinTreeParserVisitor.java:502]: I'll move the type up into a variable so it's added in both positions
